version: '3.9'
services:
  backend:
    build:
      context: ./backend   # Specify the path to the Dockerfile in the 'backend' folder
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the container

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/book-store/
    volumes:
      - /var/lib/postgresql/data/book-store/  # Mount the local 'database' directory into the container

volumes:
  backend:
  