version: '3.9'
services:
  backend:
    build:
      context: ./backend   # Specify the path to the Dockerfile in the 'backend' folder
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app  # Mount the local 'backend' directory into the container

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      PGDATA: /var/lib/postgresql/data/book-store/  # Define another default location or subdirectory for database files in container
    volumes:  # Configure volumes to be mounted into the PostgreSQL container
      - backend:/var/lib/postgresql/data/book-store/  # Mount the local 'database' directory into the container, failed previously with '/var/lib/postgresql/data folder is not empty',
      # probably because I've tried to install postgres locally before or because my dir database wasn't empty - it had schema.sgl file
      # setting env var PGDATA fixed the issue. 
      # Prev attemt to change volumes dir on '/var/lib/postgresql/data/book-store' without setting PGDATA failed

volumes:
  backend:
